# Daemon configuration
foreground: true

# Common configurations
read-only: true
allow-other: true
nonempty: false

# Dynamic profiler related configuration. This helps to root-cause high memory/cpu usage related issues.
dynamic-profile: false
profiler-port:
profiler-ip:

# Logger configuration
logging:
  type: syslog
  level: log_off
  file-path: /var/blobFuse
  max-file-size-mb:
  file-count:
  track-time: false

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - stream
  - file_cache
  - attr_cache
  - azstorage
  - loopbackfs

# Libfuse configuration
libfuse:
  default-permission: 0777
  attribute-expiration-sec:
  entry-expiration-sec: #<time kernel can cache directory listing attributes (in sec). Default - 120 sec>
  negative-entry-expiration-sec: #<time kernel can cache attributes of non existent paths (in sec). Default - 120 sec>
  fuse-trace: false #<enable libfuse api trace logs for debugging>
  extension: #<physical path to extension library>
  disable-writeback-cache: false #<disallow libfuse to buffer write requests if you must strictly open files in O_WRONLY or O_APPEND mode. alternatively, you can set ignore-open-flags.>
  ignore-open-flags: true #<ignore the append and write only flag since O_APPEND and O_WRONLY is not supported with writeback caching. alternatively, you can disable-writeback-cache. Default value is true>
  max-fuse-threads:  #<number of threads allowed at libfuse layer for highly parallel operations, Default is 128>
  direct-io: false #<enable to bypass the kernel cache>

  # Streaming configuration
stream:
  # If block-size-mb, blocks-per-file or cache-size-mb are 0, the stream component will not cache blocks.
  block-size-mb: # <for read only mode:: size of each block to be cached in memory while streaming (in MB). For read/write:: size of newly created blocks. Default - 0 MB>
  max-buffers: #<total number of buffers to store blocks in. Default - 0 MB>
  buffer-size-mb: #<size for each buffer. Default - 0>
  file-caching: #<read/write mode file level caching or handle level caching. Default - false (handle level caching ON)>

# Disk cache related configuration
file_cache:
  # Required
  path: /var/cache/blobFuse #<path to local disk cache>

  # Optional
  policy: #lru|lfu <eviction policy to be engaged for cache eviction. lru = least recently used file to be deleted, lfu = least frequently used file to be deleted. Default - lru>
  timeout-sec: #<default cache eviction timeout (in sec). Default - 120 sec>
  max-eviction: #<number of files that can be evicted at once. Default - 5000>
  max-size-mb: #<maximum cache size allowed. Default - 0 (unlimited)>
  high-threshold: #<% disk space consumed which triggers eviction. This parameter overrides 'timeout-sec' parameter and cached files will be removed even if they have not expired. Default - 80>
  low-threshold: #<% disk space consumed which triggers eviction to stop when previously triggered by the high-threshold. Default - 60>
  create-empty-file: #true|false <create an empty file on container when create call is received from kernel>
  allow-non-empty-temp: #true|false <allow non empty temp directory at startup>
  cleanup-on-start: #true|false <cleanup the temp directory on startup, if its not empty>
  policy-trace: #true|false <generate eviction policy logs showing which files will expire soon>
  offload-io: #true|false <by default libfuse will service reads/writes to files for better perf. Set to true to make file-cache component service read/write calls.>
  sync-to-flush: #true|false <sync call to a file will force upload of the contents to storage account>
  refresh-sec: #<number of seconds after which compare lmt of file in local cache and container and refresh file if container has the latest copy>

# Attribute cache related configuration
attr_cache:
  timeout-sec: #<time attributes can be cached (in sec). Default - 120 sec>
  no-cache-on-list: false # <do not cache attributes during listing, to optimize performance>
  no-symlinks: false #<to improve performance disable symlink support. symlinks will be treated like regular files.>
  max-files: false #<maximum number of files in the attribute cache at a time. Default - 5000000>

# Loopback configuration
loopbackfs:
  path: /mount-blob #<path to local directory>

# Azure storage configuration
azstorage:
# Required
  type: block #<type of storage account to be connected. Default - block>
  account-name: adfusage # <name of the storage account>
  container: retaildatawarehousecontainer # <name of the storage container to be mounted>
  endpoint:  https://adfusage.blob.core.windows.net #<storage account endpoint (example - https://account-name.blob.core.windows.net)>
  mode: key # <kind of authentication to be used>
  account-key: nPb6aYumJmVIAupoZReylhTJyjnUQ2MAQSDbL2V1zs6v3j7eCs8tzyxch5PZEgjH+JcAGhax8bKp+AStgFMaYA== #<storage account key>
  # OR
  #sas: <storage account sas>
  # OR
  #appid: <storage account app id / client id for MSI>
  #resid: <storage account resource id for MSI>
  #objid: <object id for MSI>
  # OR
  #tenantid: <storage account tenant id for SPN>
  #clientid: <storage account client id for SPN>
  #clientsecret: <storage account client secret for SPN>
  #oauth-token-path: <path to file containing the OAuth token>
  # Optional
  use-http: #true|false <use http instead of https for storage connection>
  aadendpoint: #<storage account custom aad endpoint>
  subdirectory: #<name of subdirectory to be mounted instead of whole container>
  block-size-mb: #<size of each block (in MB). Default - 16 MB>
  max-concurrency: #<number of parallel upload/download threads. Default - 32>
  tier:  # hot|cool|archive|none <blob-tier to be set while uploading a blob. Default - none>
  block-list-on-mount-sec: #<time list api to be blocked after mount (in sec). Default - 0 sec>
  max-retries: #<number of retries to attempt for any operation failure. Default - 5>
  max-retry-timeout-sec: #<maximum timeout allowed for a given retry (in sec). Default - 900 sec>
  retry-backoff-sec: #<retry backoff between two tries (in sec). Default - 4 sec>
  max-retry-delay-sec: #<maximum delay between two tries (in sec). Default - 60 sec>
  http-proxy: #ip-address:port <http proxy to be used for connection>
  https-proxy: #ip-address:port <https proxy to be used for connection>
  sdk-trace: #true|false <enable storage sdk logging>
  fail-unsupported-op: #true|false <for block blob account return failure for unsupported operations like chmod and chown>
  auth-resource: #<resource string to be used during OAuth token retrieval>
  update-md5: #true|false <set md5 sum on upload. Impacts performance. works only when file-cache component is part of the pipeline>
  validate-md5: #true|false <validate md5 on download. Impacts performance. works only when file-cache component is part of the pipeline>
  virtual-directory: #true|false <support virtual directories without existence of a special marker blob>
  disable-compression: #true|false <disable transport layer content encoding like gzip, set this flag to true if blobs have content-encoding set in container>
  max-results-for-list: #<maximum number of results returned in a single list API call while getting file attributes. Default - 2>
  honour-acl: #true|false <honour ACLs on files and directories when mounted using MSI Auth and object-ID is provided in config>

# Mount all configuration
##mountall:
#  # allowlist takes precedence over denylist in case of conflicts
#  container-allowlist:
#    -
#  container-denylist:
#    - <list of containers not to be mounted>
#
## Health Monitor configuration
#health_monitor:
#  enable-monitoring: true|false <enable health monitor>
#  stats-poll-interval-sec: <Blobfuse2 stats polling interval (in sec). Default - 10 sec>
#  process-monitor-interval-sec: <CPU, memory and network usage polling interval (in sec). Default - 30 sec>
#  output-path: <Path where health monitor will generate its output file. File name will be monitor_<pid>.json>
#  # list of monitors to be disabled
#  monitor-disable-list:
#    - blobfuse_stats <Disable blobfuse2 stats polling>
#    - file_cache_monitor <Disable file cache directory monitor>
#    - cpu_profiler <Disable CPU monitoring on blobfuse2 process>
#    - memory_profiler <Disable memory monitoring on blobfuse2 process>
#    - network_profiler <Disable network monitoring on blobfuse2 process>